Hola Jose
There have always been very creative and dedicated people in Tibia's community, who have accompanied and contributed to Tibia's growth with fansites. Read on to find out how the cooperation between Tibia and fansites started, and what you would miss out on if you never paid them a visit....
